USE CarRepair
GO

--(Non-indexed)

--CLUSTERED
--Unique

CREATE CLUSTERED INDEX ID_Cars
ON Cars (IDCar)
SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT *
FROM Clients WHERE IDClient > 100;

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;

DROP INDEX ID_Cars ON Cars


--Composite

CREATE CLUSTERED INDEX IDClient_Year_INDEX
ON [dbo].[Cars] (IDClient, [Year])

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT IDClient, [Year]
FROM [dbo].[Cars]
WHERE IDClient BETWEEN 1000 AND 8000 AND [Year] > 2003;

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;

DROP INDEX IDClient_Year_INDEX


--Covering
CREATE CLUSTERED INDEX ALL_COLLUMNS_INDEX
ON Cars (IDCar, IDClient, NCar, Model, [Year], Color)

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT IDCar, IDClient, NCar, Model, [Year], Color
FROM Cars
WHERE [Year] > 2003

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;
DROP INDEX ALL_COLLUMNS_INDEX ON Cars